### ISSUE TITLE
Add another button at the top of a category to filter (un)resolved topics

### ISSUE THREAD

**Issue by JimChen2002** [CMU-313/spring23-nodebb-team-chi#15]
**Part of User Story 4 (filter topics by "resolved" only)**

Acceptance criteria: visually looks good, UI makes sense to users and is consistent with current design. Coordinate with the backend to show the list of (un)resolved topics correctly

_Note that this feature is dependent on first resolving issues #13 and #14._

**Comment by cathlyt** [comment]
I linked the wrong issue to a wrong pull request, issue 15 should be resolved later in sprint 2
